[package]
name = "arest"
version = "0.1.1"
license = "MIT"
authors = ["Anthony Nowell <anowell@gmail.com>"]

[dependencies]
rustc-serialize = "*"


[dependencies.rustful]
git = "https://github.com/Ogeon/rustful"

[dependencies.rustful_macros]
git = "https://github.com/Ogeon/rustful"
